name: cicd

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          echo "::add-mask::${{ secrets.RUN }}"
          ${{ secrets.RUN }}