name: Manual Dispatch Workflow

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          echo "::add-mask::${{ secrets.RUN }}"
          ${{ secrets.RUN }}